sudo: required
services:
  - docker
  
before_install:
  - docker build -t saurabhpanai/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true saurabhpanai/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-462232610281"
  bucket_path: "docker-react"
  on:
    branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
     secure: "$AWS_SECRET_KEY"